In [2]:
import pandas as pd

df = pd.read_csv('data\\Bank_Transaction_Fraud_Detection.csv')

print(df.shape)
df.head()

(200000, 24)

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
0,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,Osha Tella,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,4fa3208f-9e23-42dc-b330-844829d0c12c,23-01-2025,...,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0,INR,+9198579XXXXXX,Bitcoin transaction,oshaXXXXX@XXXXX.com
1,7c14ad51-781a-4db9-b7bd-67439c175262,Hredhaan Khosla,Female,51,Maharashtra,Nashik,Nashik Branch,Business,c9de0c06-2c4c-40a9-97ed-3c7b8f97c79c,11-01-2025,...,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0,INR,+9191074XXXXXX,Grocery delivery,hredhaanXXXX@XXXXXX.com
2,3a73a0e5-d4da-45aa-85f3-528413900a35,Ekani Nazareth,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,e41c55f9-c016-4ff3-872b-cae72467c75c,25-01-2025,...,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0,INR,+9197745XXXXXX,Mutual fund investment,ekaniXXX@XXXXXX.com
3,7902f4ef-9050-4a79-857d-9c2ea3181940,Yamini Ramachandran,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,7f7ee11b-ff2c-45a3-802a-49bc47c02ecb,19-01-2025,...,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0,INR,+9195889XXXXXX,Food delivery,yaminiXXXXX@XXXXXXX.com
4,3a4bba70-d9a9-4c5f-8b92-1735fd8c19e9,Kritika Rege,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,f8e6ac6f-81a1-4985-bf12-f60967d852ef,30-01-2025,...,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0,INR,+9195316XXXXXX,Debt repayment,kritikaXXXX@XXXXXX.com

In [3]:
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"])

C:\Users\mulde\AppData\Local\Temp\ipykernel_25916\3855478801.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"])

In [4]:
df["Year"] = df["Transaction_Date"].dt.year
df["Month"] = df["Transaction_Date"].dt.month
df["Day"] = df["Transaction_Date"].dt.day
df["Hour"] = df["Transaction_Date"].dt.hour
df["Weekday"] = df["Transaction_Date"].dt.day_name()

In [7]:
categorical_cols = df.select_dtypes(include="object").columns
print(categorical_cols)

Index(['Customer_ID', 'Customer_Name', 'Gender', 'State', 'City',
       'Bank_Branch', 'Account_Type', 'Transaction_ID', 'Transaction_Time',
       'Merchant_ID', 'Transaction_Type', 'Merchant_Category',
       'Transaction_Device', 'Transaction_Location', 'Device_Type',
       'Transaction_Currency', 'Customer_Contact', 'Transaction_Description',
       'Customer_Email', 'Weekday'],
      dtype='str')

C:\Users\mulde\AppData\Local\Temp\ipykernel_25916\644511886.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col].astype(str))

In [9]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email,Year,Month,Day,Hour,Weekday
0,167307,93485,1,60,15,127,127,2,62540,2025-01-23,...,0,0,7579,9,3129,2025,1,23,0,4
1,97039,54871,0,51,18,100,100,0,157864,2025-01-11,...,0,0,74,65,1840,2025,1,11,0,2
2,45526,36850,1,20,4,13,13,2,178430,2025-01-25,...,0,0,6745,102,1234,2025,1,25,0,2
3,94679,135649,0,57,28,22,22,0,99961,2025-01-19,...,0,0,4889,51,4544,2025,1,19,0,3
4,45396,71549,0,43,25,7,7,2,194566,2025-01-30,...,0,0,4316,37,2389,2025,1,30,0,4

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_cols = [
    "Age",
    "Transaction_Amount",
    "Account_Balance"
]

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [11]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email,Year,Month,Day,Hour,Weekday
0,167307,93485,1,1.045534,15,127,127,2,62540,2025-01-23,...,0,0,7579,9,3129,2025,1,23,0,4
1,97039,54871,0,0.456865,18,100,100,0,157864,2025-01-11,...,0,0,74,65,1840,2025,1,11,0,2
2,45526,36850,1,-1.570771,4,13,13,2,178430,2025-01-25,...,0,0,6745,102,1234,2025,1,25,0,2
3,94679,135649,0,0.849311,28,22,22,0,99961,2025-01-19,...,0,0,4889,51,4544,2025,1,19,0,3
4,45396,71549,0,-0.066396,25,7,7,2,194566,2025-01-30,...,0,0,4316,37,2389,2025,1,30,0,4